dynamo:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  LFJ1_position_controller:
    type: effort_controllers/JointPositionController
    joint: LFJ1
    pid: {p: 100.0, i: 2, d: 0.2}
  LFJ2_position_controller:
    type: effort_controllers/JointPositionController
    joint: LFJ2
    pid: {p: 100.0, i: 2, d: 0.2}
  LFJ3_position_controller:
    type: effort_controllers/JointPositionController
    joint: LFJ3
    pid: {p: 100.0, i: 2, d: 0.2}

  LBJ1_position_controller:
    type: effort_controllers/JointPositionController
    joint: LBJ1
    pid: {p: 100.0, i: 2, d: 0.2}
  LBJ2_position_controller:
    type: effort_controllers/JointPositionController
    joint: LBJ2
    pid: {p: 100.0, i: 2, d: 0.2}
  LBJ3_position_controller:
    type: effort_controllers/JointPositionController
    joint: LBJ3
    pid: {p: 100.0, i: 2, d: 0.2}

  RFJ1_position_controller:
    type: effort_controllers/JointPositionController
    joint: RFJ1
    pid: {p: 100.0, i: 2, d: 0.2}
  RFJ2_position_controller:
    type: effort_controllers/JointPositionController
    joint: RFJ2
    pid: {p: 100.0, i: 2, d: 0.2}
  RFJ3_position_controller:
    type: effort_controllers/JointPositionController
    joint: RFJ3
    pid: {p: 100.0, i: 2, d: 0.2}

  RBJ1_position_controller:
    type: effort_controllers/JointPositionController
    joint: RBJ1
    pid: {p: 100.0, i: 2, d: 0.2}
  RBJ2_position_controller:
    type: effort_controllers/JointPositionController
    joint: RBJ2
    pid: {p: 100.0, i: 2, d: 0.2}
  RBJ3_position_controller:
    type: effort_controllers/JointPositionController
    joint: RBJ3
    pid: {p: 100.0, i: 2, d: 0.2}