dynamo:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  LFJ1_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_shoulder
    pid: {p: 3000000.0, i: 0.01, d: 90000}
  LFJ2_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_leg
    pid: {p: 3000000.0, i: 0.01, d: 90000}
  LFJ3_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_left_foot
    pid: {p: 3000000.0, i: 0.01, d: 90000}

  LBJ1_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_shoulder
    pid: {p: 3000000.0, i: 0.01, d: 90000}
  LBJ2_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_leg
    pid: {p: 3000000.0, i: 0.01, d: 90000}
  LBJ3_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_left_foot
    pid: {p: 3000000.0, i: 0.01, d: 90000}

  RFJ1_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_shoulder
    pid: {p: 3000000.0, i: 0.01, d: 90000}
  RFJ2_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_leg
    pid: {p: 3000000.0, i: 0.01, d: 90000}
  RFJ3_position_controller:
    type: effort_controllers/JointPositionController
    joint: front_right_foot
    pid: {p: 3000000.0, i: 0.01, d: 90000}

  RBJ1_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_shoulder
    pid: {p: 3000000.0, i: 0.01, d: 90000}
  RBJ2_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_leg
    pid: {p: 3000000.0, i: 0.01, d: 90000}
  RBJ3_position_controller:
    type: effort_controllers/JointPositionController
    joint: rear_right_foot
    pid: {p: 3000000.0, i: 0.01, d: 90000}